controller_list:
  - name: fake_hand_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_5
      - joint_6
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
initial:  # Define initial robot poses per group
  - group: hand_group
    pose: hand_closed
  - group: arm_group
    pose: zero_pose